"""Statement changed

Revision ID: 861e3993cc4e
Revises: 
Create Date: 2020-02-10 21:30:51.451785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '861e3993cc4e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('statement', 'subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statement', sa.Column('subject', mysql.VARCHAR(length=255), nullable=False))
    # ### end Alembic commands ###
